---
## (1)所属グループ作成
- name: main / Create new groups
  group:
    name: "{{ item.value.groups }}"
  with_dict: "{{ user_newusers }}"

## (2)新規ユーザ作成
- name: main / Create new users
  user:
    name: "{{ item.key }}"
    password: "{{ item.value.pass }}"
    shell: /bin/bash
    home: "/home/{{ item.key }}"
    state: present
    groups: "{{ item.value.groups }}"
  with_dict: "{{ user_newusers }}"

## (3)公開鍵登録
- name: main / Distribute authorized key
  authorized_key:
    user: "{{ item.key }}"
<<<<<<< HEAD
    key: "{{ lookup('file', '/tmp/ansible_pubkey/id_rsa.pub') }}"
=======
    key: "{{ lookup('file', '~/root/.ssh/id_rsa.pub') }}"
>>>>>>> f7438dd0359ff8d2660f5bc24f772e32a2211189
  with_dict: "{{ user_newusers }}"

## (4)システム権限の付与
- name: main / Deploy temporary sudoers files
  template:
    src: "{{ item.value.priv }}_sudoers.j2"
    dest: "/etc/sudoers.d/{{ item.key }}"
    owner: root
    group: root
    mode: 0400
    validate: 'visude -c -f %s'
  with_dict:  "{{ user_newusers }}"